# Makefile pro spuštění serveru pro překlad doménových jmen.
# Autor: Michal Šedý <xsedym02>
# Příkazem make run se spustí server na portu 8888.
# Post se dá specifikovat parametrem PORT=
#    např: make run PORT=1234

PY=python3.6
PROG=src/server.py
PORT=8888

run:
	$(PY) $(PROG) $(PORT)