using Nemocnice.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nemocnice.DatabaseDataCreator
{
    public class AllergyCreator
    {
        public void AllergyCreate(DatabaseContext db)
        {
            db.AllergyT.Add(AllergyAdd("Alergie na kov", "Alergie na kov se projevuje zarudnutím pokožky v oblastech kde se dotýká kovu, nebo v jeho blízkém okolí. Může se objevit jen mírné podráždění a začervenání, stejně jako mohou vyskákat svědivé pupínky nebo se objeví mokvající puchýřky."));
            db.AllergyT.Add(AllergyAdd("Alergie na hmyzí bodnutí", "Hmyzí bodnutí může vyvolat reakci celkovou, kdy se nejen v místě vpichu, ale i po celém těle může objevit urtikarielní exantém. Může dojít k projevům jako je ucpání nosu, svědění očí, otok hrdla s obtížným polykáním a dušností. Nejtěžší reakcí je anafylaktický šok. Alergické reakce mohou být v místě v pichu, kdy se na kůži objeví svědivý pupen, který se zvětšuje popřípadě erytém, či edém. Pokud je v kůži přítomno žihadlo (po  bodnutí včelou), je nutno jej okamžitě odstranit a kůži desinfikovat. K tomu, aby nedocházelo k šíření hmyzího jedu dále do organismu, je doporučováno zaškrcení končetiny nad místem vpichu. K ošetření této lokální reakce stačí přiložení chladného obkladu a podání celkově antihistaminik (p.o.)."));
            db.AllergyT.Add(AllergyAdd("Alergie na plíseň", "Především obecně známé projevy, jako je rýma, svědění nosu, kýchání, zánět očních spojivek, slzení, ekzém (nejčastěji v podobě ložisek na hlavě, v kolenních a loketních jamkách), chronický kašel a astma, bolest hlavy, někdy také spánkové potíže a pocit únavy."));
            db.AllergyT.Add(AllergyAdd("Alergie na citrusy", "Mezi projevy alergie patří svědění, bolestivá kůže, začervenání a vznik šupinek - tak imunitní systém bojuje proti infekci, vyvolané kosmetickou složkou. Jakmile se alergenu vyhnete, příznaky by měly za několik dnů polevit."));
            db.AllergyT.Add(AllergyAdd("Alergie na trávy a seno", "Pacienty trápívá kýchání, svědění nosu, vodnatá sekrece, někdy výrazné zduření sliznic, které brání dýchání nosem. Časté jsou také potíže oční a dále svědění či pálení v krku a záchvaty kašle či dušnosti s pískoty na hrudi, což už jsou projevy astmatu. Mohou se vyskytnout také projevy kožní (kopřivka, ekzém) i celkové (únava, zvýšená teplota, bolesti hlavy)."));
            db.AllergyT.Add(AllergyAdd("Alergie na pyl", "Nejčastějším projevem alergie na pyl je takzvaná senná rýma, neboli sezónní alergická rýma. Poznáme ji hlavně podle kýchání 10 – 30x za sebou, tvorby vodnatého hlenu oteklé nosní sliznice, pocitu ucpaného a svědivého nosu a rýmy. Aby toho nebylo už tak dost, obvykle se ještě přidá alergický zánět očních spojivek doprovázený nepříjemným slzením, pálením a svěděním očí. Mezi další projevy pylové alergie patří svědění v ústech, krku nebo uších, problémy s polykáním, snížená chuť k jídlu, ekzémová vyrážka především na hlavě, podkolenních a loketních jamkách, spánkové potíže, nespavost, pocit únavy, zvýšená teplota nebo bolest hlavy způsobená ucpáním nosu.Časté jsou také záchvaty kašle, které se mohou projevit i jako nezadržitelný astmatický záchvat."));
            db.AllergyT.Add(AllergyAdd("Alergie na zvířata (zejména kočky a psy)", "Vlastní alergickou reakci vůbec nespouštějí zvířecí chlupy. Podstatně více jsou za ni zodpovědné látky, které zvíře produkuje, většinou bílkoviny v kožním mazu, slinách a moči. Když se zvíře myje, nanese sliny a další látky na srst. Mimo to se tyto alergizující látky (alergeny) mohou smísit s prachem na zemi. Alergeny se pak dostávají do vzduchu a mohou vyvolat alergickou reakci po vdechnutí, i bez přímého kontaktu člověka se zvířetem. Chlupy kočky jsou obzvláště nebezpečné: jsou tak měkké a lehké, že všude zůstávájí a těžko se dají odstranit. Obrovským semeništěm chlupů jsou např. čalouněná sedadla v kinech. Proto mají alergici často potíže i v místech, kde se normálně žádná zvířata nevyskytují - chlupy přinese do kina člověk, který doma chová kočku, po něm si na sedadlo sedne alergik a dojde k reakci. U takových pacientů je pak rozpoznání příčiny alergie obzvláště těžké, a velice často je možnost alergie na zvířata zcela opomenuta."));
            db.AllergyT.Add(AllergyAdd("Alergie na ryby", "Alergie na ryby může postihnout děti, mladistvé i dospělé. U dětí a mladistvých představují ryby pátou nejčastější potravinovou alergii. Zatímco alergie na mléko nebo vajíčka v průběhu dospívání vymizí, alergie na ryby ve většině případech přetrvává až do dospělého věku. Jedná se tedy o trvalou diagnózu, kdy nedochází ke odeznění či alespoň zlepšení nemoci.Pouze u 10 % postižených lze hovořit o zmírnění alergické reakce a celkovém zlepšení stavu. První příznaky se obvykle objeví pár minut po požití ryby, ve výjimečných případech 24 až 48 hodin poté.Projevy jsou velmi podobné jako u ostatních alergií.Při stanovení diagnózy a léčby je proto velmi důležité najít tu správnou příčinu problémů. Mezi klasické příznaky patří: žaludeční a střevní problémy, kožní reakce, otok hrtanu, dýchací problémy. Ve vyjímečných případech může dojít až na anafylaktický šok."));
            db.AllergyT.Add(AllergyAdd("Alergie na jod", "Pokud je člověk alergický na jód, může si příznaky splést s kožními problémy. Alergie nebo přecitlivělost na jód se totiž nejčastěji projevuje vznikem vyrážky na pokožce. Může jít o slabý ekzém, v nejhorších případech hrozí i životu nebezpečný anafylaktický šok."));
            db.AllergyT.Add(AllergyAdd("Alergie na lepek", "Rozdíl mezi alergií na lepek a intolerancí lepku už je patrný v označení. Alergií nazýváme zvýšenou citlivost na jakoukoliv látku, v tomto případě máme na mysli lepek. Alergie je vlastně nepřiměřená reakce imunitního systému. Nejčastěji alergií na lepek trpí malé děti. Problémy se projevují krátce nebo jen pár hodin po požití potravin obsahující lepek. Celiakie se může projevit v každém věku od dětí až po dospělé a příznaky se objeví po delší době od konzumace potraviny s lepkem."));
            db.AllergyT.Add(AllergyAdd("Alergie na slunce", "Ve skutečnosti alergie na sluneční záření není skutečnou alergií. Při pravé alergii si postižený organismus vyrábí větší množství protilátek (IgE), než opravdu potřebuje. Společně s alergenem pak způsobují nepřiměřenou reakci imunitního systému. V případě slunce však ke vzniku potíží dochází trochu jinak. Potíže vznikají okamžitě nebo krátce po dopadu slunečních paprsků na lidskou pokožku, které u citlivějších osob vyvolají vznik látek způsobujících viditelné změny na pokožce(např.svědivé pupínky, ekzémy, vyrážky).Na první pohled projevy sluneční alergie připomínají typickou alergickou reakci, proto se mezi lidmi ujalo označení alergie na slunce.Správně by se mělo používat označení solární ekzém."));
            db.AllergyT.Add(AllergyAdd("Alergie na mléko", "Alergie na mléko (setkat se můžete i s výrazem alergie na laktózu) se ale může objevit i u dospělého člověka. Mírnější formy alergií se projevují středně těžkými příznaky. Horší případy přechází v chronické záněty trávicího systému, které mohou způsobit problém s trávením a hubnutí. Postižení by měli z jídelníčku vyloučit mléko a mléčné produkty a nahradit je vhodnými alternativami."));
            db.AllergyT.Add(AllergyAdd("Alergie na roztoče/prach", "Člověk, kterému roztoči vadí, mívá chronické potíže s dýchacími cestami včetně malých průdušek. Alergie na roztoče má proto velký vliv na vznik průduškového astmatu. Negativně ovlivnit však může i další nemoci jako například chronický atopický ekzém. Kvůli neustále přítomnosti roztočů řadíme alergii na roztoče mezi tzv. pereniální (celoroční) alergie. Mezi klasické příznaky patří nachlazení a rýma, zánět spojivek, průduškové astma, ekzém, nekvalitní spánek a únava."));
            db.AllergyT.Add(AllergyAdd("Alergie na léky", "Léková alergie se nejčastěji projevuje na kůži, objevit se ale mohou i dýchací a trávící obtíže a úplně v nejhorším případě může člověku postihnout anafylaktický šok, který zasahuje více než jeden orgán. Ta vyžaduje okamžitou lékařskou pomoc."));
            db.SaveChanges();
        }
        private Allergy AllergyAdd(string name, string description)
        {
            return new Allergy { Name = name, Description = description,};
        }
    }
}
